### ISSUE TITLE
Problem with loading FID

### ISSUE THREAD

**Issue by minnten** [isi-nmr/brukerapi-python#5]
Hello, 

I tried to use your API to load a FID. 
To try it, I used your example here https://github.com/isi-nmr/brukerapi-python/blob/master/examples/read_fid.ipynb

all works, till I try `print(dataset.TE)` there the error message is AttributeError: 'Dataset' object has no attribute 'TE'

perhaps you have a clue, where I made a mistake.
I'm running on version 0.1.2.0

Thanks Minnten

**Comment by tomas-psorn** [comment]
Hello Minnten, there is a mistake in the notebook, the TE property is not yet defined for the fid dataset type in v0.1.2.0. I'm about to issue a new version of the API within a couple of days and it will come with a broader collection of properties, including the TE. I'll let you know once it's out. Thank you for opening the issue.

Tom
